version: '2'
services:
  ghost:
    image: ghost:0.11.3
    restart: always
    environment:
      NODE_ENV: production
    volumes:
      - ./ghost:/var/lib/ghost

  caddy:
    image: abiosoft/caddy:0.9.3
    restart: always
    volumes:
      - ./caddy/Caddyfile:/etc/Caddyfile:ro
      - ./caddy/.caddy:/root/.caddy:rw
    ports:
      - "80:80"
      - "443:443"
    links:
      - ghost
